In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('telco_churn.csv')

df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [21]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [22]:
df.head(10)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False

In [23]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [24]:
df.index

RangeIndex(start=0, stop=3333, step=1)

In [25]:
df.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

In [26]:
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
count,3333.000000,3333.000000,3333.000000,3323.000000,3323.000000,3315.000000,3324.000000,3325.000000,3333.000000,3333.000000,3332.000000,3333.000000,3333.000000,3333.000000,3328.000000,3328.000000
mean,101.064806,437.182418,8.099010,179.787150,100.456214,30.557831,201.033935,100.110677,17.083540,200.872037,100.115246,9.039325,10.237294,4.479448,2.764588,1.563101
std,39.822106,42.371290,13.688365,54.419625,20.057356,9.255987,50.676652,19.932115,4.310668,50.573847,19.566710,2.275873,2.791840,2.461214,0.754086,1.315870
min,1.000000,408.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.200000,33.000000,1.040000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,408.000000,0.000000,143.700000,87.000000,24.420000,166.600000,87.000000,14.160000,167.000000,87.000000,7.520000,8.500000,3.000000,2.300000,1.000000
50%,101.000000,415.000000,0.000000,179.400000,101.000000,30.500000,201.400000,100.000000,17.120000,201.200000,100.000000,9.050000,10.300000,4.000000,2.780000,1.000000
75%,127.000000,510.000000,20.000000,216.500000,114.000000,36.780000,235.325000,114.000000,20.000000,235.300000,113.000000,10.590000,12.100000,6.000000,3.270000,2.000000
max,243.000000,510.000000,51.000000,350.800000,165.000000,59.640000,363.700000,170.000000,30.910000,395.000000,175.000000,17.770000,20.000000,20.000000,5.400000,9.000000

In [27]:
df.describe(include=object)

       State International plan Voice mail plan  Churn
count   3333               3333            3333   3325
unique    51                  2               2      2
top       WV                 No              No  False
freq     106               3010            2411   2842

In [28]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [29]:
df["International plan"]

0        No
1        No
2        No
3       Yes
4       Yes
       ...
3328     No
3329     No
3330     No
3331    Yes
3332     No
Name: International plan, Length: 3333, dtype: object

In [32]:
df[["State", "Voice mail plan"]]

     State Voice mail plan
0       KS             Yes
1       OH             Yes
2       NJ              No
3       OH              No
4       OK              No
...    ...             ...
3328    AZ             Yes
3329    WV              No
3330    RI              No
3331    CT              No
3332    TN             Yes

[3333 rows x 2 columns]

In [34]:
df.get(["State", "Voice mail plan"])

     State Voice mail plan
0       KS             Yes
1       OH             Yes
2       NJ              No
3       OH              No
4       OK              No
...    ...             ...
3328    AZ             Yes
3329    WV              No
3330    RI              No
3331    CT              No
3332    TN             Yes

[3333 rows x 2 columns]

In [37]:
df.State.unique()

array(['KS', 'OH', 'NJ', 'OK', 'AL', 'MA', 'MO', 'LA', 'WV', 'IN', 'RI',
       'IA', 'MT', 'NY', 'ID', 'VT', 'VA', 'TX', 'FL', 'CO', 'AZ', 'SC',
       'NE', 'WY', 'HI', 'IL', 'NH', 'GA', 'AK', 'MD', 'AR', 'WI', 'OR',
       'MI', 'DE', 'UT', 'CA', 'MN', 'SD', 'NC', 'WA', 'NM', 'NV', 'DC',
       'KY', 'ME', 'MS', 'TN', 'PA', 'CT', 'ND'], dtype=object)

In [40]:
df[df["Voice mail plan"] == "No"]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326,OH,96,415,No,No,0,106.6,128.0,18.12,284.8,87.0,24.21,178.9,92.0,8.05,14.9,7,4.02,1.0,False
3327,SC,79,415,No,No,0,134.7,98.0,22.90,189.7,68.0,16.12,221.4,128.0,9.96,11.8,5,3.19,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False

In [48]:
df.query("State == 'AK'")

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
36,AK,36,408,No,Yes,30,146.3,128.0,NaN,NaN,NaN,13.81,129.3,109.0,5.82,14.5,6,3.92,0.0,False
38,AK,136,415,Yes,Yes,33,203.9,106.0,NaN,NaN,NaN,15.95,101.7,107.0,4.58,10.5,6,2.84,3.0,False
95,AK,104,408,No,No,0,278.4,106.0,47.33,81.0,113.0,6.89,163.2,137.0,7.34,9.8,5,2.65,1.0,False
138,AK,127,510,No,Yes,36,183.2,117.0,31.14,126.8,76.0,10.78,263.3,71.0,11.85,11.2,8,NaN,NaN,NaN
181,AK,126,415,No,No,0,58.2,94.0,9.89,138.7,118.0,11.79,136.8,91.0,6.16,11.9,1,3.21,5.0,True
282,AK,48,415,No,Yes,37,211.7,115.0,35.99,159.9,84.0,13.59,144.1,80.0,6.48,12.2,1,3.29,1.0,False
339,AK,78,408,No,No,0,225.1,67.0,38.27,199.2,127.0,16.93,175.5,102.0,7.90,14.6,2,3.94,0.0,False
350,AK,59,510,No,No,0,182.5,104.0,31.03,204.7,95.0,17.40,229.9,100.0,10.35,11.3,8,3.05,4.0,False
353,AK,117,415,No,No,0,181.5,95.0,30.86,205.1,88.0,17.43,204.0,82.0,9.18,14.7,9,3.97,2.0,False
505,AK,41,415,No,No,0,159.3,66.0,27.08,125.9,75.0,10.70,261.9,76.0,11.79,11.1,5,3.00,1.0,False
550,AK,111,415,No,No,0,172.8,58.0,29.38,183.1,108.0,15.56,158.8,104.0,7.15,7.9,3,2.13,4.0,True
657,AK,130,415,No,No,0,242.5,101.0,41.23,102.8,114.0,8.74,142.4,89.0,6.41,9.3,2,2.51,2.0,False
684,AK,110,408,No,No,0,100.1,90.0,17.02,233.3,93.0,19.83,204.4,57.0,9.20,11.1,8,3.00,3.0,False
718,AK,127,408,No,No,0,182.3,124.0,30.99,169.9,110.0,14.44,184.0,116.0,8.28,9.3,3,2.51,1.0,False
719,AK,78,510,No,No,0,190.3,88.0,32.35,194.5,89.0,16.53,256.5,109.0,11.54,11.7,5,3.16,2.0,False
812,AK,156,510,No,No,0,123.7,96.0,21.03,103.0,80.0,8.76,189.4,82.0,8.52,13.1,4,3.54,1.0,False
950,AK,108,415,No,No,0,103.0,129.0,17.51,242.3,103.0,20.60,170.2,89.0,7.66,7.9,3,2.13,1.0,False
953,AK,132,415,No,Yes,39,175.7,93.0,29.87,187.2,94.0,15.91,225.5,118.0,10.15,8.6,3,2.32,2.0,False
1024,AK,146,510,Yes,No,0,133.0,65.0,22.61,262.8,93.0,22.34,214.3,128.0,9.64,11.2,3,3.02,1.0,False
1054,AK,50,408,No,No,0,183.6,107.0,31.21,58.6,118.0,4.98,202.6,99.0,9.12,8.7,3,2.35,1.0,False
1094,AK,115,415,No,No,0,245.2,105.0,41.68,159.0,109.0,13.52,229.9,74.0,10.35,7.2,8,1.94,0.0,False
1162,AK,173,510,No,No,0,172.5,78.0,29.33,142.6,91.0,12.12,102.0,63.0,4.59,10.9,2,2.94,0.0,False
1224,AK,120,415,No,No,0,178.4,97.0,30.33,168.3,113.0,14.31,120.5,93.0,5.42,9.3,9,2.51,1.0,False
1260,AK,76,415,No,Yes,22,160.1,107.0,27.22,168.7,136.0,14.34,23.2,102.0,1.04,9.5,4,2.57,3.0,False
1342,AK,52,415,No,Yes,24,170.9,71.0,29.05,201.4,80.0,17.12,159.0,124.0,7.15,4.1,5,1.11,2.0,False
1417,AK,141,408,No,No,0,83.2,74.0,14.14,190.6,104.0,16.20,150.5,79.0,6.77,10.7,7,2.89,1.0,False
1589,AK,76,415,No,No,0,143.7,55.0,24.43,173.1,108.0,14.71,239.1,95.0,10.76,5.8,6,1.57,1.0,False
1682,AK,96,408,No,Yes,29,150.0,91.0,25.50,159.4,75.0,13.55,228.1,55.0,10.26,8.5,3,2.30,1.0,False
1803,AK,101,510,No,No,0,174.9,105.0,29.73,262.0,75.0,22.27,210.0,93.0,9.45,8.5,5,2.30,1.0,False
1884,AK,51,510,Yes,Yes,12,135.8,60.0,23.09,200.6,134.0,17.05,192.4,98.0,8.66,12.3,7,3.32,2.0,False
1987,AK,59,408,No,No,0,159.5,96.0,27.12,167.2,123.0,14.21,138.6,106.0,6.24,10.2,4,2.75,0.0,False
2071,AK,132,510,No,No,0,181.1,121.0,30.79,314.4,109.0,26.72,246.7,81.0,11.10,4.2,9,1.13,2.0,False
2083,AK,52,510,No,No,0,148.3,83.0,25.21,181.6,79.0,15.44,155.6,104.0,7.00,8.3,6,2.24,3.0,False
2101,AK,110,415,No,No,0,148.4,95.0,25.23,193.8,98.0,16.47,206.0,106.0,9.27,6.9,6,1.86,0.0,False
2222,AK,97,415,No,Yes,24,176.1,109.0,29.94,159.4,81.0,13.55,269.1,94.0,12.11,12.1,9,3.27,0.0,False
2265,AK,126,415,No,Yes,31,278.0,88.0,47.26,253.2,65.0,21.52,223.2,114.0,10.04,8.7,4,2.35,0.0,False
2269,AK,138,415,No,Yes,37,75.8,102.0,12.89,173.6,147.0,14.76,162.6,96.0,7.32,8.2,13,2.21,0.0,False
2270,AK,146,415,No,No,0,195.9,86.0,33.30,228.6,82.0,19.43,303.5,94.0,13.66,12.2,4,3.29,3.0,False
2367,AK,74,415,No,No,0,262.3,114.0,44.59,198.9,96.0,16.91,165.9,90.0,7.47,6.6,5,1.78,3.0,False
2418,AK,115,415,No,No,0,210.6,120.0,35.80,153.1,84.0,13.01,262.2,79.0,11.80,11.0,5,2.97,0.0,False
2475,AK,1,408,No,No,0,175.2,74.0,29.78,151.7,79.0,12.89,230.5,109.0,10.37,5.3,3,1.43,1.0,False
2571,AK,103,510,No,No,0,190.9,62.0,32.45,226.6,53.0,19.26,230.1,96.0,10.35,7.8,3,2.11,2.0,False
2627,AK,86,408,No,No,0,150.8,85.0,25.64,295.9,88.0,25.15,247.2,104.0,11.12,12.5,1,3.38,1.0,False
2752,AK,55,408,No,Yes,39,139.3,101.0,23.68,178.3,117.0,15.16,246.5,104.0,11.09,8.1,1,2.19,3.0,False
2807,AK,52,408,No,No,0,217.0,104.0,36.89,152.3,83.0,12.95,134.3,109.0,6.04,11.8,4,3.19,2.0,False
2902,AK,61,415,No,Yes,15,252.4,106.0,42.91,187.8,69.0,15.96,259.6,137.0,11.68,10.0,3,2.70,2.0,False
2929,AK,71,510,No,No,0,185.0,84.0,31.45,232.5,129.0,19.76,191.1,82.0,8.60,14.9,4,4.02,3.0,False
3088,AK,100,415,No,Yes,29,213.6,127.0,36.31,175.9,82.0,14.95,207.2,100.0,9.32,8.9,3,2.40,1.0,False
3137,AK,58,510,No,No,0,131.9,96.0,22.42,167.6,107.0,14.25,205.9,106.0,9.27,14.7,5,3.97,3.0,False
3236,AK,121,408,No,Yes,34,245.0,95.0,41.65,216.9,66.0,18.44,112.4,125.0,5.06,7.5,8,2.03,0.0,False
3241,AK,177,415,Yes,No,0,248.7,118.0,42.28,172.3,73.0,14.65,191.9,87.0,8.64,11.3,2,3.05,1.0,True
3283,AK,99,510,No,No,0,238.4,96.0,40.53,246.5,130.0,20.95,198.4,117.0,8.93,12.4,4,3.35,3.0,False

In [50]:
df.query("`International plan` == 'No' and State == 'KS'")

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
179,KS,70,408,No,No,0,232.1,122.0,39.46,292.3,112.0,24.85,201.2,112.0,9.05,0.0,0,0.00,3.0,False
287,KS,137,408,No,No,0,205.9,88.0,35.00,209.3,86.0,17.79,289.9,84.0,13.05,14.5,4,3.92,2.0,False
368,KS,132,415,No,No,0,83.4,110.0,14.18,232.2,137.0,19.74,146.7,114.0,6.60,7.6,5,2.05,1.0,False
379,KS,127,415,No,No,0,221.0,100.0,37.57,160.7,113.0,13.66,233.1,96.0,10.49,6.8,4,1.84,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,KS,164,510,No,Yes,30,238.8,100.0,40.60,230.0,121.0,19.55,206.3,66.0,9.28,13.2,8,3.56,1.0,False
3244,KS,101,415,No,No,0,231.3,87.0,39.32,224.7,88.0,19.10,214.6,69.0,9.66,7.2,7,1.94,1.0,False
3253,KS,127,415,No,Yes,24,154.8,69.0,26.32,177.2,105.0,15.06,207.6,102.0,9.34,9.0,4,2.43,1.0,False
3285,KS,57,415,No,No,0,158.1,117.0,26.88,115.2,149.0,9.79,182.4,92.0,8.21,11.8,7,3.19,0.0,False
3287,KS,170,415,No,Yes,42,199.5,119.0,33.92,135.0,90.0,11.48,184.6,49.0,8.31,10.9,3,2.94,4.0,True

In [52]:
df[(df["International plan"] == "No") & (df["State"] == "KS")]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
179,KS,70,408,No,No,0,232.1,122.0,39.46,292.3,112.0,24.85,201.2,112.0,9.05,0.0,0,0.00,3.0,False
287,KS,137,408,No,No,0,205.9,88.0,35.00,209.3,86.0,17.79,289.9,84.0,13.05,14.5,4,3.92,2.0,False
368,KS,132,415,No,No,0,83.4,110.0,14.18,232.2,137.0,19.74,146.7,114.0,6.60,7.6,5,2.05,1.0,False
379,KS,127,415,No,No,0,221.0,100.0,37.57,160.7,113.0,13.66,233.1,96.0,10.49,6.8,4,1.84,2.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,KS,164,510,No,Yes,30,238.8,100.0,40.60,230.0,121.0,19.55,206.3,66.0,9.28,13.2,8,3.56,1.0,False
3244,KS,101,415,No,No,0,231.3,87.0,39.32,224.7,88.0,19.10,214.6,69.0,9.66,7.2,7,1.94,1.0,False
3253,KS,127,415,No,Yes,24,154.8,69.0,26.32,177.2,105.0,15.06,207.6,102.0,9.34,9.0,4,2.43,1.0,False
3285,KS,57,415,No,No,0,158.1,117.0,26.88,115.2,149.0,9.79,182.4,92.0,8.21,11.8,7,3.19,0.0,False
3287,KS,170,415,No,Yes,42,199.5,119.0,33.92,135.0,90.0,11.48,184.6,49.0,8.31,10.9,3,2.94,4.0,True

index com iloc

df.iloc[index da linha]

In [53]:
df.iloc[14]

State                        IA
Account length               62
Area code                   415
International plan           No
Voice mail plan              No
Number vmail messages         0
Total day minutes           NaN
Total day calls             NaN
Total day charge            NaN
Total eve minutes         307.2
Total eve calls            76.0
Total eve charge          26.11
Total night minutes       203.0
Total night calls          99.0
Total night charge         9.14
Total intl minutes         13.1
Total intl calls              6
Total intl charge          3.54
Customer service calls      4.0
Churn                     False
Name: 14, dtype: object

In [58]:
df.iloc[14,4]

'No'

In [62]:
df.iloc[10:20, [0,1,3]]

   State  Account length International plan
10    IN              65                 No
11    RI              74                 No
12    IA             168                 No
13    MT              95                 No
14    IA              62                 No
15    NY             161                 No
16    ID              85                 No
17    VT              93                 No
18    VA              76                 No
19    TX              73                 No

In [65]:
new_df = df.copy()

new_df.set_index("State", inplace=True)

new_df.head()

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [68]:
new_df.loc[["KS", "AK"], "Area code"]

State
KS    415
KS    408
KS    408
KS    408
KS    415
     ...
AK    415
AK    510
AK    408
AK    415
AK    510
Name: Area code, Length: 122, dtype: int64

In [71]:
new_df.iloc[10:20, [0,5]]

       Account length  Total day minutes
State
IN                 65              129.1
RI                 74              187.7
IA                168                NaN
MT                 95                NaN
IA                 62                NaN
NY                161                NaN
ID                 85                NaN
VT                 93                NaN
VA                 76                NaN
TX                 73                NaN